### PR TITLE
Expanded Compat Layer, New Addon Support, Optimised Imports

### PR DESCRIPTION
**Pull request by chronosacaria**
__Additions__
 - Added `BlocksRegistry`
 - Added `CompoundTagUtils`
 - Added `HeatableBlockEntity`
 - Added `ItemStackInventory`
 - Added `ModItemSettings`
 - Added `SlotInvalidRangeException`
 - Added `SoundsRegistry`
 - Added `SyncedBlockEntity`
 - Added `TagsRegistry`

__Merges__
 - Merged `Configuration`
 - Merged `FarmersDelightMod`
 - Merged `Foods`
 - Merged `ItemsRegistry`
 - Merged `KnifeItem`
 - Merged `PieBlock`
 - Merged `WildPatchBlock`

__Changes__
 - Changed `this.stateDefinition` -> `getStateDefinition()`
 - Changed `FabricBlockSettings.copyOf` -> `BlockBehaviour.Properties.copy` wherever possible

### CODE REVIEW

**Comment by chronosacaria** [comment]
These changes allowed for the following add-ons to load without any apparent issues:
- Cake Delight
- Casualness Delight
- Expanded Delight
- Nether's Delight
- Ube's Delight

I tried my best to find ways to crash it once I got it working, but I couldn't do it, in the end. However, it is always very possible that I missed something

**Comment by MehVahdJukaar** [comment]
Nice, seems very extensive. Looks good to me.
Also optimize imports goes brr XD

**Comment by chronosacaria** [comment]
I'll be adding more support once tax season is over 😅 Thanks for the merge!

**Comment by MehVahdJukaar** [comment]
Thanks for contributing! Will surely help with the move. I know many of those mods have already created a compat version for FDRF but a couple others are still missing. To my knowledge might just be two or so

**Pull request merged**
