### PR TITLE
Update es_mx.json

### PR DESCRIPTION
**Pull request by TheLegendofSaram**
Adds all of the missing translations and changes the "lienzo" to "canvas"  and "betabel" to "remolacha" to be more accurate

### CODE REVIEW

**Comment by cerealconjugo** [comment]
actually "betabel" was accurate, if you play with Español México and look at the item Betroot its translated on vanilla to "Betabel" not "remolacha"

**Comment by cerealconjugo** [comment]
canvas, In other hand, its right to be translated as "Lienzo" I think its more common to be called or referred to it in that way that actually calling it "canvas"

**Comment by TheLegendofSaram** [comment]
Okk, I didn't even notice about the "betabel" not being "remolacha" in Español MX, I'll look into it tomorrow. And about the "canvas" I have always know the fabric as "canvas", and "lienzo" (which is the same fabric), was always use in the context of art, so I thought it would be more appropriate to use the "generic" fabric name for the mod. But idk, If you really want me change it back to "lienzo" I'll have no problem doing so

**Comment by cerealconjugo** [comment]
just the "remolacha" string, the canvas one you can leave it how you think its better

**Pull request merged**
